version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080" # Map backend's port to host
    networks:
      app-network:
        aliases:
          - backend
    environment:
      - GIN_MODE=debug # Optional: Set Gin's mode to debug for detailed logs

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80" # Map frontend's port to localhost:3000
    networks:
      app-network:
        aliases:
          - frontend

networks:
  app-network:
    driver: bridge
